### ISSUE TITLE
how to use in clapper player?

### ISSUE THREAD

**Issue by hj338** [SxtBox/zee5_Dot_Com_Streaming#1]
hi bro...
your work is good i like it bro.
but i want sum help

in this link formet is like this ok
/api/Get_Streams.php?url=https://z5ams.akamaized.net/hindustan/index.m3u8

but in this formet its not working in clapper player

but i want in this formet
/api/Get_Streams.php?c=andpicssd&e=.m3u8

i dont now how to please help.
And Thankyou

**Comment by SxtBox** [comment]
Check repo again, I created Clappr Player for you!!!

**Comment by hj338** [comment]
Thankyou Bro once again u are awesome bro really thankyou..

**Comment by hj338** [comment]
can u give hotstar also?

**Comment by SxtBox** [comment]
> can u give hotstar also?

if you have preferences you can tell me what you want at trc4@usa.com
